#[path = "calls/storage_array.rs"] mod storage_array;
pub(crate) use storage_array::*;
#[path = "calls/value_transfer.rs"] mod value_transfer;
pub(crate) use value_transfer::*;
#[path = "calls/low_level.rs"] mod low_level;
pub(crate) use low_level::*;
#[path = "calls/type_constructors.rs"] mod type_constructors;
pub(crate) use type_constructors::*;
#[path = "calls/struct_constructors.rs"] mod struct_constructors;
pub(crate) use struct_constructors::*;
#[path = "calls/builtins.rs"] mod builtins;
pub(crate) use builtins::*;
#[path = "calls/member_calls.rs"] mod member_calls;
pub(crate) use member_calls::*;
#[path = "calls/variable_calls.rs"] mod variable_calls;
pub(crate) use variable_calls::*;
#[path = "calls/dispatch.rs"] mod dispatch;
pub(crate) use dispatch::*;
