fn try_lower_runtime_member_builtin(
    base: &Identifier,
    member: &Identifier,
    args: &[Expression],
    ctx: &mut LoweringContext,
    instructions: &mut Vec<Instruction>,
) -> Option<bool> {
    if base.name != "Runtime" {
        return None;
    }

    match member.name.as_str() {
        "initializeServices" => {
            if !args.is_empty() {
                ctx.record_error(format!(
                    "Runtime.initializeServices requires 0 argument(s), got {}",
                    args.len()
                ));
                return Some(false);
            }

            // The devpack exposes Runtime.initializeServices() as a convenience initializer,
            // but builtin libraries are compiler intrinsics and their Solidity bodies are
            // not compiled. Treat this helper as a no-op so devpack-based sources remain
            // portable while keeping the generated bytecode minimal.
            instructions.push(Instruction::PushLiteral(LiteralValue::Boolean(true)));
            Some(true)
        }
        "notifyIndexed" => {
            if args.len() != 3 {
                ctx.record_error(format!(
                    "Runtime.notifyIndexed requires 3 argument(s), got {}",
                    args.len()
                ));
                return Some(false);
            }

            // notifyIndexed(eventName, topics, data) => notify(eventName, abi.encode(topics, data))
            if !lower_expression(&args[0], ctx, instructions) {
                return Some(false);
            }
            if !lower_expression(&args[1], ctx, instructions) {
                return Some(false);
            }
            if !lower_expression(&args[2], ctx, instructions) {
                return Some(false);
            }

            instructions.push(Instruction::CallBuiltin {
                builtin: BuiltinCall::AbiEncode,
                arg_count: 2,
            });
            validate_runtime_notify_call(
                &[
                    args[0].clone(),
                    Expression::FunctionCall(
                        Default::default(),
                        Box::new(Expression::MemberAccess(
                            Default::default(),
                            Box::new(Expression::Variable(Identifier {
                                loc: Default::default(),
                                name: "abi".to_string(),
                            })),
                            Identifier {
                                loc: Default::default(),
                                name: "encode".to_string(),
                            },
                        )),
                        vec![args[1].clone(), args[2].clone()],
                    ),
                ],
                ctx,
            );
            instructions.push(Instruction::CallBuiltin {
                builtin: BuiltinCall::RuntimeNotify,
                arg_count: 2,
            });
            Some(true)
        }
        _ => None,
    }
}
