impl SemanticAnalyzer {
    fn is_builtin(&self, name: &str) -> bool {
        matches!(
            name,
            "add"
                | "sub"
                | "mul"
                | "div"
                | "mod"
                | "eq"
                | "lt"
                | "gt"
                | "iszero"
                | "and"
                | "or"
                | "xor"
                | "not"
                | "byte"
                | "shl"
                | "shr"
                | "sar"
                | "keccak256"
                | "sha256"
                | "ripemd160"
                | "ecrecover"
                | "mload"
                | "mstore"
                | "sload"
                | "sstore"
                | "caller"
                | "callvalue"
                | "calldataload"
                | "calldatasize"
                | "gas"
                | "gasprice"
                | "origin"
                | "address"
                | "balance"
                | "timestamp"
                | "number"
                | "blockhash"
                | "coinbase"
                | "log0"
                | "log1"
                | "log2"
                | "log3"
                | "log4"
                | "call"
                | "delegatecall"
                | "staticcall"
                | "return"
                | "revert"
        )
    }
}

