fn resolve_builtin_call(expr: &Expression) -> Option<BuiltinCall> {
    if let Expression::MemberAccess(_, inner, member) = expr {
        if let Expression::Variable(base) = inner.as_ref() {
            let member_name = member.name.as_str();
            match base.name.as_str() {
                "Runtime" => return resolve_runtime_member(member_name),
                "abi" => return resolve_abi_member(member_name),
                "Storage" => return resolve_storage_member(member_name),
                "Syscalls" => return resolve_syscalls_member(member_name),
                "NativeCalls" => return resolve_native_calls_member(member_name),
                "Neo" => return resolve_neo_member(member_name),
                _ => {}
            }
        }
    }

    if let Expression::Variable(identifier) = expr {
        if identifier.name == "ecrecover" {
            return Some(BuiltinCall::Ecrecover);
        }
        if identifier.name == "keccak256" {
            return Some(BuiltinCall::Keccak256);
        }
        if identifier.name == "type" {
            return Some(BuiltinCall::TypeOf);
        }
    }

    None
}

fn builtin_library_supported_members(base: &str) -> Option<&'static [&'static str]> {
    match base {
        "Runtime" => Some(&[
            "notify",
            "notifyIndexed",
            "checkWitness",
            "gasLeft",
            "burnGas",
            "log",
            "getTime",
            "getTrigger",
            "getInvocationCounter",
            "getCurrentSigners",
            "getCallFlags",
            "getScriptContainer",
            "loadScript",
            "initializeServices",
        ]),
        "abi" => Some(&["encode", "encodePacked", "encodeCall", "encodeWithSignature", "decode"]),
        "Storage" => Some(&[
            "find",
            "put",
            "get",
            "remove",
            "findLocal",
            "putLocal",
            "getLocal",
            "removeLocal",
            "asReadOnly",
            "initializeContext",
            "getContext",
            "getReadOnlyContext",
            "getUsage",
            "putContractMetadata",
        ]),
        "Syscalls" => Some(&[
            "contractCall",
            "contractCallWithFlags",
            "getCallFlags",
            "contractCreate",
            "contractUpdate",
            "contractDestroy",
            "createStandardAccount",
            "createMultisigAccount",
            "notify",
            "getCurrentIndex",
            "getCurrentHash",
            "getBlock",
            "getTransaction",
            "getTransactionHeight",
            "getTransactionFromBlock",
            "getTransactionSigners",
            "getTransactionVMState",
            "getExecutingScriptHash",
            "getCallingScriptHash",
            "getEntryScriptHash",
            "getScriptContainer",
            "loadScript",
            "getStorageContext",
            "getReadOnlyStorageContext",
            "storageAsReadOnly",
            "storageGet",
            "storagePut",
            "storageDelete",
            "storageFind",
            "storageGetLocal",
            "storagePutLocal",
            "storageDeleteLocal",
            "storageFindLocal",
            "checkWitness",
            "getTime",
            "gasLeft",
            "getPlatform",
            "getTrigger",
            "getNotifications",
            "log",
            "getCurrentSigners",
            "checkSig",
            "checkMultisig",
            "sha256",
            "ripemd160",
            "verifyWithECDsa",
            "murmur32",
            "keccak256",
            "recoverSecp256K1",
            "verifyWithEd25519",
            "bls12381Serialize",
            "bls12381Deserialize",
            "bls12381Equal",
            "bls12381Add",
            "bls12381Mul",
            "bls12381Pairing",
            "serialize",
            "deserialize",
            "itoa",
            "atoi",
            "jsonSerialize",
            "jsonDeserialize",
            "base64Encode",
            "base64Decode",
            "base64UrlEncode",
            "base64UrlDecode",
            "base58Encode",
            "base58Decode",
            "base58CheckEncode",
            "base58CheckDecode",
            "hexEncode",
            "hexDecode",
            "memoryCompare",
            "memorySearch",
            "stringSplit",
            "strLen",
            "iteratorNext",
            "iteratorValue",
            "getCurrentRandom",
            "getNetwork",
            "getAddressVersion",
            "burnGas",
            "getInvocationCounter",
            "getFeePerByte",
            "getExecFeeFactor",
            "getExecPicoFeeFactor",
            "getStoragePrice",
            "getMillisecondsPerBlock",
            "getMaxValidUntilBlockIncrement",
            "getMaxTraceableBlocks",
            "getAttributeFee",
            "isBlocked",
            "oracleRequest",
            "getOraclePrice",
            "getDesignatedByRole",
            "scriptHashToAddress",
            "addressToScriptHash",
            "isValidAddress",
            "getContractScript",
            "contractExists",
        ]),
        "NativeCalls" => Some(&[
            "neoTotalSupply",
            "neoBalanceOf",
            "neoTransfer",
            "neoDecimals",
            "neoSymbol",
            "vote",
            "getCandidates",
            "registerCandidate",
            "unregisterCandidate",
            "getGasPerBlock",
            "getRegisterPrice",
            "setRegisterPrice",
            "setGasPerBlock",
            "getAccountState",
            "unclaimedGas",
            "getCandidateVote",
            "getCommittee",
            "getCommitteeAddress",
            "isCommittee",
            "getNextBlockValidators",
            "getAllCandidates",
            "isValidator",
            "gasTotalSupply",
            "gasBalanceOf",
            "gasTransfer",
            "gasDecimals",
            "gasSymbol",
            "deployContract",
            "updateContract",
            "destroyContract",
            "getContract",
            "listContracts",
            "hasMethod",
            "getMinimumDeploymentFee",
            "setMinimumDeploymentFee",
            "getContractById",
            "isContract",
            "getFeePerByte",
            "setFeePerByte",
            "getExecFeeFactor",
            "getExecPicoFeeFactor",
            "setExecFeeFactor",
            "getStoragePrice",
            "getMillisecondsPerBlock",
            "setMillisecondsPerBlock",
            "getMaxValidUntilBlockIncrement",
            "setMaxValidUntilBlockIncrement",
            "getMaxTraceableBlocks",
            "setMaxTraceableBlocks",
            "getAttributeFee",
            "setAttributeFee",
            "setStoragePrice",
            "blockAccount",
            "unblockAccount",
            "isBlocked",
            "getBlockedAccounts",
            "recoverFund",
            "setWhitelistFeeContract",
            "removeWhitelistFeeContract",
            "getWhitelistFeeContracts",
            "requestOracleData",
            "getOraclePrice",
            "setOraclePrice",
            "oracleFinish",
            "oracleVerify",
            "designateAsRole",
            "getDesignatedByRole",
            "currentIndex",
            "currentHash",
            "getBlock",
            "getTransaction",
            "getTransactionHeight",
            "getTransactionFromBlock",
            "getTransactionSigners",
            "getTransactionVMState",
            "notaryVerify",
            "notaryBalanceOf",
            "notaryExpirationOf",
            "notaryLockDepositUntil",
            "notaryWithdraw",
            "notaryGetMaxNotValidBeforeDelta",
            "notarySetMaxNotValidBeforeDelta",
            "notaryOnNEP17Payment",
            "treasuryVerify",
            "treasuryOnNEP17Payment",
            "treasuryOnNEP11Payment",
            "isNativeContract",
            "getNativeContractName",
            "getAllNativeContracts",
            "estimateNativeCallGas",
            "batchNativeCalls",
            "getNetworkConfiguration",
            "getNativeContractManifest",
            "safeNativeCall",
            "externalNativeCall",
        ]),
        "Neo" => Some(&[
            "verifySignature",
            "callContract",
            "deployContract",
            "getNeoBalance",
            "getGasBalance",
            "getGasPrice",
            "getStoragePrice",
            "getCommittee",
            "getValidators",
            "isCommittee",
            "isValidator",
            "getRandom",
        ]),
        _ => None,
    }
}

fn resolve_runtime_member(member: &str) -> Option<BuiltinCall> {
    match member {
        "notify" => Some(BuiltinCall::RuntimeNotify),
        "checkWitness" => Some(BuiltinCall::RuntimeCheckWitness),
        "gasLeft" => Some(BuiltinCall::Syscall("System.Runtime.GasLeft".to_string())),
        "burnGas" => Some(BuiltinCall::Syscall("System.Runtime.BurnGas".to_string())),
        "log" => Some(BuiltinCall::Syscall("System.Runtime.Log".to_string())),
        "getTime" => Some(BuiltinCall::Syscall("System.Runtime.GetTime".to_string())),
        "getTrigger" => Some(BuiltinCall::Syscall("System.Runtime.GetTrigger".to_string())),
        "getInvocationCounter" => Some(BuiltinCall::Syscall(
            "System.Runtime.GetInvocationCounter".to_string(),
        )),
        "getCurrentSigners" => Some(BuiltinCall::Syscall(
            "System.Runtime.CurrentSigners".to_string(),
        )),
        "getCallFlags" => Some(BuiltinCall::Syscall(
            "System.Contract.GetCallFlags".to_string(),
        )),
        "getScriptContainer" => Some(BuiltinCall::Syscall(
            "System.Runtime.GetScriptContainer".to_string(),
        )),
        "loadScript" => Some(BuiltinCall::Syscall("System.Runtime.LoadScript".to_string())),
        _ => None,
    }
}

fn resolve_abi_member(member: &str) -> Option<BuiltinCall> {
    match member {
        "encode" => Some(BuiltinCall::AbiEncode),
        "encodePacked" => Some(BuiltinCall::AbiEncodePacked),
        "encodeCall" => Some(BuiltinCall::AbiEncodeCall),
        "encodeWithSignature" => Some(BuiltinCall::AbiEncodeWithSignature),
        "decode" => Some(BuiltinCall::AbiDecode),
        _ => None,
    }
}

fn resolve_storage_member(member: &str) -> Option<BuiltinCall> {
    match member {
        "find" => Some(BuiltinCall::StorageFind),
        "put" => Some(BuiltinCall::StoragePut),
        "get" => Some(BuiltinCall::StorageGet),
        "remove" => Some(BuiltinCall::StorageDelete),
        "findLocal" => Some(BuiltinCall::Syscall("System.Storage.Local.Find".to_string())),
        "putLocal" => Some(BuiltinCall::Syscall("System.Storage.Local.Put".to_string())),
        "getLocal" => Some(BuiltinCall::Syscall("System.Storage.Local.Get".to_string())),
        "removeLocal" => Some(BuiltinCall::Syscall("System.Storage.Local.Delete".to_string())),
        "initializeContext" => Some(BuiltinCall::Syscall("System.Storage.GetContext".to_string())),
        "getContext" => Some(BuiltinCall::Syscall("System.Storage.GetContext".to_string())),
        "getReadOnlyContext" => Some(BuiltinCall::Syscall(
            "System.Storage.GetReadOnlyContext".to_string(),
        )),
        "asReadOnly" => Some(BuiltinCall::Syscall("System.Storage.AsReadOnly".to_string())),
        _ => None,
    }
}

fn resolve_neo_member(member: &str) -> Option<BuiltinCall> {
    match member {
        "verifySignature" => Some(BuiltinCall::VerifySignature),
        "callContract" => Some(BuiltinCall::ContractCall),
        "deployContract" => Some(BuiltinCall::DeployContract),
        "getNeoBalance" => Some(BuiltinCall::NativeCall {
            contract: NativeContract::Neo,
            method: "balanceOf".to_string(),
        }),
        "getGasBalance" => Some(BuiltinCall::NativeCall {
            contract: NativeContract::Gas,
            method: "balanceOf".to_string(),
        }),
        "getGasPrice" => Some(BuiltinCall::NativeCall {
            contract: NativeContract::Policy,
            method: "getFeePerByte".to_string(),
        }),
        "getStoragePrice" => Some(BuiltinCall::NativeCall {
            contract: NativeContract::Policy,
            method: "getStoragePrice".to_string(),
        }),
        "getCommittee" => Some(BuiltinCall::NativeCall {
            contract: NativeContract::Neo,
            method: "getCommittee".to_string(),
        }),
        "getRandom" => Some(BuiltinCall::Syscall("System.Runtime.GetRandom".to_string())),
        _ => None,
    }
}
